#!/bin/bash

# Date, Time and the TimeZone
TODAY=`date +%Y/%m/%d-%T-%Z`
CREATEDDATE=${TODAY:2:8}
CREATEDDATE=${CREATEDDATE//\//}

DEFAULT_EDITOR="vim"
DEFAULT_REMOTE="origin"
DEFAULT_BRANCH="master"

if [ "$#" -eq 1 ] && [ $1 == "commit" ]; then
    git add -A
    git commit -m "These are what I learned in $TODAY."
    read -r -p "Cool man! Do you want to push it to repo? [Y/n] " response
    if [ -z $response ] || [[ $response =~ ^(yes|y|Y|YES) ]]; then
        git push $DEFAULT_REMOTE $DEFAULT_BRANCH
    fi
    echo -e "\033[92mKeep moving forward! >>>"
    exit 0
fi

if [ "$#" -lt 2 ]; then
    echo "You must enter at least 2 arguments, first is category, next one is subject, and the last is your Editor (default: $DEFAULT_EDITOR)"
    exit 1
fi

CATEGORY=${1// /-}
SUBJECT=$2
EDITOR=${3:-$DEFAULT_EDITOR}
## Filename: The same as subject, except for replace all space with dash
## and lowercase all chars.
FILENAME=${SUBJECT// /-}
FILENAME=${FILENAME,,}
## The full filename will be something like below with pattern: %y%m%d-filename
## 160508-this-is-a-subject.md
MDFILE=$CATEGORY/$CREATEDDATE-$FILENAME.md

[ -d $CATEGORY ] || mkdir $CATEGORY
[ -f $MDFILE ] && echo -e "\n---\n" >> $MDFILE
echo "- Date: $TODAY" >> $MDFILE
echo "- Tags: #$CATEGORY" >> $MDFILE
# Avoid to add a addition newline
echo -e "\n\c" >> $MDFILE
echo "## $SUBJECT" >> $MDFILE
echo -e "\n\n" >> $MDFILE

echo -e "\n\c"
echo -e "\tTell me what you learned today about '$1: $2' ;) Then commit it by \033[92m./til commit"
echo -e "\n\c"

# Check if the editor is the default one then launch it and put the cursor exactly at edit point
if [ $EDITOR == $DEFAULT_EDITOR ]
then
    let "EDITLINE=`wc -l $MDFILE | cut -d" " -f1` - 1"
    $EDITOR +$EDITLINE $MDFILE
else
    $EDITOR $MDFILE
fi

